Nv = 2
print("Nv =", Nv)
Na = 2
print("Na =", Na)
Ni = 2
print("Ni =", Ni)
Va = [0, 1, 2]
print("Va =", Va)
Ov = [0, 1, 2]
print("Ov =", Ov)
Dv = [0, 2, 1]
print("Dv =", Dv)
Td = [0, 8, 12]
print("Td =", Td)
Ta = [0, 9, 13]
print("Ta =", Ta)
Dt = [[0, 0, 0], [0, 2, 25], [0, 25, 2]]
print("Dt =", Dt)
Dtinf = 25
print("Dtinf =", Dtinf)
Np = [0, 80, 80]
print("Np =", Np)
Nec = [0, 2, 2]
print("Nec =", Nec)
Pr = [0, 100, 100]
print("Pr =", Pr)
Ne = 5
print("Ne =", Ne)
Ty = [1, 1, 0, 0, 0]
print("Ty =", Ty)
Vh = [1, 1, 1, 1, 2]
print("Vh =", Vh)
Nvmax = 2
print("Nvmax =", Nvmax)
Dmax = 7
print("Dmax =", Dmax)
Dda = 2
print("Dda =", Dda)
